[workspace]
members = ["opgen", "opgen-test"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
opgen = { version = "0.1.0", path = "opgen" }

[profile.dev.build-override]
opt-level = 0
codegen-units = 256
debug = true